# -*- coding: utf-8 -*-
"""Tarea5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1McEcC-MjpYjTgagoB7m2KqLjSiE5vxhc
"""

def  hora ():
    hora = 0
    hrsymins = []
    palindromo = []
    while hora < 24:
        for minutos in range (60):
            if hora <=9 and minutos <= 9:
                a = (f"0{hora}:0{minutos}")
                hrsymins.append(a)
                if str(a) == str (a)[::-1]:
                    palindromo.append(a)
            if hora <= 9 and minutos > 9:
                a =(f"0{hora}:{minutos}")
                hrsymins.append(a)
                if str(a) == str (a)[::-1]:
                    palindromo.append(a)
            if hora > 9 and minutos > 9:
                a = (f"{hora}:{minutos}")
                hrsymins.append(a)
                if str(a) == str (a)[::-1]:
                    palindromo.append(a)
            if minutos == 59:
                hora += 1
    print(hrsymins)
    print(f"Exiten {len(palindromo)} horas palindromas")  
    print(f"LAS HORAS PALINDROMAS SON: {palindromo}")     
hora()