# -*- coding: utf-8 -*-
"""Tarea1_ADA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MXVz1lvQW8ueT09TGIJX9nV748IBJ5_t
"""

class NodoTriple:
    def __init__(self, value , left= None, center=None, rigth =None):
        self.data = value
        self.left = left 
        self.center = center 
        self.rigth = rigth

arbol = NodoTriple(20, left = NodoTriple(23, left = None, center = NodoTriple(57), rigth = None ),\
                   center = NodoTriple(19, left = None, center = None , rigth = NodoTriple(67, center = NodoTriple(99))  ),\
                   rigth = None)

head = arbol
print(head.left.center.data)
print(head.center.rigth.center.data)