# -*- coding: utf-8 -*-
"""Tarea8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12g0hoECDYhMPvJCz9AiiypYpkxvSEGCo

Elaborar un algoritmo por fuerza bruta que sirva para descifrar el siguiente texto que se encuentra en cifrado césar:

Si Cupdmzaplil Uikpwuis Icbwuwti lm Tmfpkw oi lmamtxmvilw cu xixms xzwbiñwupkw mu si opabwzpi g mu si nwztikpwu lm ucmabzw xipa Sia bizmia acabiubpdia lm mabi puabpbckpwu xcjspki icbwuwti g sipki awu si lwkmukpi si pudmabpñikpwu g si lpncapwu lm si kcsbczi
Mu ms tculw ikilmtpkw ma zmkwuwkpli kwtw cui cupdmzaplil lm mfkmsmukpi Si CUIT zmaxwulm is xzmamubm g tpzi ms ncbczw kwtw ms xzwgmkbw kcsbczis tia ptxwzbiubm lm Tmfpkw
Si CUIT ma cu maxikpw lm spjmzbilma Mu mssi am xzikbpki kwbplpiuitmubm ms zmaxmbw si bwsmziukpi g ms lpiswñw Si xsczisplil lm plmia g lm xmuaitpmubw ma ixzmkpili kwtw apñuw lm ac zpycmhi g ucuki kwtw nikbwz lm lmjpsplil

- La entrega será el link del repositorio Github que contenga el proyecto del algoritmo junto con su ejecución.
"""

def cifrado_cesar(mensaje):
    alfabeto = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ"
    
    for clave in range (1, len(alfabeto)):
        cifrado = "" 
        for letra in mensaje.upper():
            if letra in alfabeto:
                indice = alfabeto.find(letra)
                indice -= clave
                if indice <0:
                    indice += 27
                cifrado += alfabeto[indice]
            else:
                cifrado += letra
        print(f"Clave: {clave} - {cifrado}")
cifrado_cesar("Si Cupdmzaplil Uikpwuis Icbwuwti lm Tmfpkw oi lmamtxmvilw cu xixms xzwbiñwupkw mu si opabwzpi g mu si nwztikpwu lm ucmabzw xipa. Sia bizmia acabiubpdia lm mabi puabpbckpwu xcjspki, icbwuwti g sipki awu si lwkmukpi, si pudmabpñikpwu g si lpncapwu lm si kcsbczi. Mu ms tculw ikilmtpkw ma zmkwuwkpli kwtw cui cupdmzaplil lm mfkmsmukpi. Si CUIT zmaxwulm is xzmamubm g tpzi ms ncbczw kwtw ms xzwgmkbw kcsbczis tia ptxwzbiubm lm Tmfpkw. Si CUIT ma cu maxikpw lm spjmzbilma. Mu mssi am xzikbpki kwbplpiuitmubm ms zmaxmbw, si bwsmziukpi g ms lpiswñw. Si xsczisplil lm plmia g lm xmuaitpmubw ma ixzmkpili kwtw apñuw lm ac zpycmhi g ucuki kwtw nikbwz lm lmjpsplil.")